### ISSUE TITLE
Task 'test' not found in root project 'app'.

### ISSUE THREAD

**Issue by nickleus73** [qlik-trial/gradle-docker#6]
Hi, 

I try your gradle-docker, but when I execute this command : 

`docker run -v $(pwd):/app qlik/gradle test`

I have this log : 

`FAILURE: Build failed with an exception.
- What went wrong:
  Task 'test' not found in root project 'app'.
- Try:
  Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.63 secs`

Have you any ideas why I can't use this command ?

Thanks for your return.
Nicolas

**Comment by hairyhenderson** [comment]
@nickleus73 - it's hard to tell from that output, and without knowing what your build file looks like, but I can think of a few troubleshooting tips:
1. Run `gradle test` in the same directory (assuming you have gradle installed locally) and see if it behaves differently. This'll tell you whether or not Docker or the `qlik/gradle` image are misbehaving.
2. If you get correct behaviour from that, make sure the bind-mount is happening as expected. Run something like `docker run -v $(pwd):/app alpine ls /app` to see what's _actually_ being mounted. If it's not what you expect, there's a number of things that could be going on.

**Comment by hairyhenderson** [comment]
This is deprecated now - use the `gradle` docker image now instead.
